export {
  PersonalFeedScopeConflictError,
  PersonalFeedScopeInputError,
  PersonalFeedScopeStoreError,
} from './errors.ts'

export {
  candidateIdentity,
  runRequestIdentity,
  sourceIdentity,
  sourceStableReference,
} from './identity.ts'

export {
  createCandidateMaterialProjection,
  createCurrentContextProjection,
  createMechanicalAdmission,
  createPeriodBusinessFinalizer,
  createRunOpportunityLifecycle,
} from './components.ts'

export {
  createCrossSourceEditor,
  type ContextEnabledCrossSourceEditorOptions,
  type CrossSourceEditorOptions,
} from './cross-source-editor.ts'

export {
  createDeliveryAndReceipt,
  type DeliveryAndReceipt,
  type DeliveryAndReceiptOptions,
} from './delivery-and-receipt.ts'

export type { PeriodBusinessFinalizer, PeriodBusinessScopeFinalizer } from './components.ts'

export {
  createPersonalFeedScopeService,
  type PersonalFeedScopeServiceOptions,
} from './service.ts'

export {
  createSourceCandidateReportReader,
  type SourceCandidateReportReader,
  type SourceCandidateReportReaderOptions,
  type SourceCandidateReportReaderResult,
} from './source-candidate-report.ts'

export { createPeriodScopeStore, type PeriodScopeStore } from './store.ts'

export type {
  C01Accepted,
  C01Result,
  C02Accepted,
  C02Result,
  C03Result,
  C08Result,
  C09Result,
  C10Accepted,
  C10Result,
  C11Accepted,
  C11Result,
  C16Accepted,
  C16Result,
  C26Accepted,
  C26Result,
  C32Accepted,
  C32Result,
  C33Accepted,
  C33Result,
  C34Accepted,
  C34Result,
  C35Accepted,
  C35Result,
  C36Accepted,
  C36Result,
  CandidateAcceptedIntoPeriod,
  CandidateMaterial,
  CandidateIdentity,
  AdmissionCandidateBasis,
  AdmissionSourceFacts,
  AdmissionSourceFactsAccepted,
  MechanicalCandidate,
  MaterialSourceFacts,
  SourceStableReference,
  CandidateMaterialProjection,
  CandidatePeriodBusinessFinalizerOptions,
  CandidateReportingWindow,
  CandidateReportingWindowAccepted,
  CandidateReportingWindowIdentity,
  ContractResult,
  ConfiguredCurrentContextProjection,
  ContextEnabledCrossSourceEditor,
  CurrentContextEditorOptions,
  ContextUnavailable,
  CurrentContext,
  CurrentContextClue,
  CurrentContextProjection,
  CurrentContextProjectionPeriodScopeEstablished,
  CurrentContextResult,
  CurrentContextResultReceiver,
  ExternalPeriodScopeInput,
  ExternalRunOpportunity,
  ExternalRunOpportunityOrigin,
  ExternalRunStartFact,
  CrossSourceEditor,
  EditingInputAccepted,
  MechanicalAdmission,
  MechanicalAdmissionPeriodScopeEstablished,
  MechanicalAdmissionPeriodScopeRequest,
  MaterialProjectionReportScope,
  MaterialProjectionReportScopeEstablished,
  MaterialFact,
  MaterialFactRecorded,
  MaterialFormed,
  MaterialUnavailable,
  PeriodEstablished,
  PeriodIdentity,
  PeriodReference,
  PeriodScopeEstablished,
  PeriodBusinessFinalizerOptions,
  PeriodStartNotice,
  PersonalFeedScopeService,
  ReportedMaterialCandidate,
  RunIdentity,
  RunOpportunityRequest,
  RunRequestIdentity,
  SourceIdentity,
  SourceCandidateReference,
  SourceCandidateReport,
  SourceCandidateReportAccepted,
  SourceCandidateReportFinalizer,
  ScreenedSourceCandidateReport,
  ScreenedMaterialCandidate,
  ScreenedMaterialCandidateAccepted,
  SourceScopeComponents,
  UnscreenedMaterialCandidate,
  UnscreenedMaterialCandidateAccepted,
  UnscreenedSourceCandidateReport,
  MaterialBasisAccepted,
  MaterialCandidate,
  CandidateDispositionReceiver,
  CandidateDispositionValue,
  CandidateEditingDecision,
  CompleteCandidateEditingDecisions,
  DispositionBasisAccepted,
  EditedFeedContent,
  EditingFailure,
  EditingConclusionIdentity,
  EditingInputClosure,
  EditingInputClosureAccepted,
  EditingInputClosureReceiver,
  FeedContentDeliveryObjectIdentity,
  DeliveryChannelResult,
  DisplayFact,
  RecentDeduplicationBasisAccepted,
  FormalFeedContentDeliveryReceipt,
  RunFeedContentDeliveryMeaningRecorded,
  PeriodDeliveryResultRecorded,
  RunFinalizationAccepted,
  BusinessFinalization,
  OrdinaryContentFinalized,
  NormalEmptyPeriodFinalized,
  EditingFailedFinalized,
  AllCandidateMaterialsUnavailableFinalized,
  PreContentPeriodSendFailedFinalized,
  FormalCandidateDisposition,
  FormalContentDeliveryReceiver,
  BusinessFinalizationReceiver,
  FormalEditingConclusion,
  FormalEditingFailureConclusion,
  FormalEmptyFeedConclusion,
  FormalEmptyFeedContent,
  FormalFeedContent,
  FormalFeedContentConclusion,
  FormalFeedContentDeliveryAccepted,
  FormalFeedContentDeliveryOwnerRead,
  FormalFeedContentDeliveryRequest,
  FormalOrdinaryFeedContent,
  EmptyCandidateSelection,
  SelectedCandidateSet,
  SourceDispositionValue,
  RawFeedContentConclusion,
  RawFeedContentInput,
  RawEmptyFeedConclusion,
  RawEditingConclusion,
  RawEditingFailureConclusion,
  SourceClosureAccepted,
  SourceDispositionState,
  C15Result,
  C17Result,
  C18Result,
  C19Result,
  C20FormalFeedContentResult,
  C21Result,
  C28Result,
  C23Result,
  C37Result,
} from './types.ts'
