import { describe, expect, it } from 'vitest'
import { mkdtemp } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { ExplorationStore } from '../src/store.ts'
import { registerExploreTools } from '../src/tools.ts'

const recordArgs = { operation: 'keep', title: 'Pi', hook: 'cache', currentFinding: 'finding', nextQuestion: 'why', citations: ['https://x.com/a/status/1'], signal: 'explicit_interest' }

describe('exploration tools', () => {
  it('registers exact tools and default query remains active-only', async () => { const definitions: Array<Record<string, unknown>> = []; const store = new ExplorationStore(await mkdtemp(join(tmpdir(), 'dsh-explore-'))); const dispose = registerExploreTools({ tools: { register: definition => { definitions.push(definition as Record<string, unknown>); return () => undefined } } }, store); expect(definitions.map(def => def.name)).toEqual(['exploration_record', 'exploration_query']); const query = definitions[1]!.execute as (args: Record<string, unknown>) => Promise<{ ok: boolean; items?: unknown[] }>; expect(await query({})).toMatchObject({ ok: true, items: [] }); dispose() })
  it('rejects dismissed/all without query and runtime limits outside 1..20', async () => { const definitions: Array<Record<string, unknown>> = []; const store = new ExplorationStore(await mkdtemp(join(tmpdir(), 'dsh-explore-'))); registerExploreTools({ tools: { register: definition => { definitions.push(definition as Record<string, unknown>); return () => undefined } } }, store); const query = definitions[1]!.execute as (args: Record<string, unknown>) => Promise<{ code?: string }>; for (const args of [{ state: 'all' }, { limit: 0 }, { limit: 21 }]) expect(await query(args)).toMatchObject({ code: 'invalid_input' }) })
  it('record/query presenters tolerate bad args, malformed durable meta, and isError ToolResults', async () => { const definitions: Array<Record<string, unknown>> = []; const store = new ExplorationStore(await mkdtemp(join(tmpdir(), 'dsh-explore-'))); registerExploreTools({ tools: { register: definition => { definitions.push(definition as Record<string, unknown>); return () => undefined } } }, store); for (const definition of definitions) { const args = definition.name === 'exploration_record' ? recordArgs : {}; expect(() => (definition.presentCall as Function)(null)).not.toThrow(); expect(() => (definition.output as { presentationMeta: Function }).presentationMeta(null, { ok: false, code: 'ledger_unavailable' })).not.toThrow(); expect(() => (definition.presentResult as Function)(args, { content: [], isError: false, meta: { old: true } })).not.toThrow(); expect((definition.presentResult as Function)(args, { content: [], isError: true, meta: { ok: true } }).title).toMatch(/失败/) } })
  it('replays durable ToolResult.meta for record and query instead of a nonexistent presentationMeta field', async () => { const definitions: Array<Record<string, unknown>> = []; const store = new ExplorationStore(await mkdtemp(join(tmpdir(), 'dsh-explore-'))); registerExploreTools({ tools: { register: definition => { definitions.push(definition as Record<string, unknown>); return () => undefined } } }, store); const record = definitions[0]!; const query = definitions[1]!; expect((record.presentResult as Function)(recordArgs, { content: [], isError: false, meta: { ok: true, state: 'active' } }).title).toBe('已更新探索候选'); expect((query.presentResult as Function)({}, { content: [], isError: false, meta: { ok: true, count: 2, state: 'active', degraded: false } }).title).toBe('找到 2 项探索候选') })
})
